//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        public string DeliveryNoteID { get; set; }
        public string AccountantID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Accountant Accountant { get; set; }
        public virtual Order Order { get; set; }
    }
}
